libvirt: add "kernel-module-control" plug
Attaching ports with hardware offloading currently fails
as Libvirt attempts to load the VF driver:

   Failed to load PCI driver module mlx5_vfio_pci: modprobe:
   ERROR: could not insert 'mlx5_vfio_pci': Operation not permitted

To address this, we'll leverage the "kernel-module-control"
snap interface.

(cherry picked from commit 5e8766b922720f4440cf49110683095055be1d06)
Signed-off-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>